server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Needed to let vue handle
    location / {
        try_files $uri /index.html;
    }

    # Redirect /game to game.html
        location /game {
            try_files /game.html =404;
        }
}
